import { DM_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "next-themes";
import { CustomScrollbar } from "@/components/custom-scrollbar";
import { Toaster } from "sonner";
import { Footer } from "@/components/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat", // hanya untuk class tertentu
  subsets: ["latin"],
});

const nunito = DM_Sans({
  variable: "--font-nunito",     // digunakan sebagai default
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "GEC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${nunito.className} ${montserrat.variable}  antialiased`}
      >
        <ThemeProvider enableSystem attribute={'class'}>
          <Navbar>
            {children}
            <Footer />
          </Navbar>
          <Toaster position="top-right" richColors />
          <CustomScrollbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
